[theme]
primaryColor="#C0392B"          # light red accent (Bosch red tone)
backgroundColor="#F7F7F7"       # very light grey background
secondaryBackgroundColor="#E5E5E5"  # soft grey panels/sidebars
textColor="#000000"             # black font
font="sans serif"
